import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'gu';

const translations = {
  en: {
    dashboard: 'Dashboard',
    purchase: 'Purchase',
    consumption: 'Consumption',
    history: 'History',
    logs: 'Logs',
    reports: 'Reports',
    items: 'Items',
    logout: 'Logout',
    all: 'All',
    app_title: 'Bhakti Gruh Udhyog',
    add_purchase: 'Add New Purchase',
    add_consumption: 'Add New Consumption',
    date: 'Date',
    source: 'Source',
    chalan_no: 'Chalan No',
    bill_no: 'Bill No',
    expiry_date: 'Expiry Date (Optional)',
    unit: 'Unit',
    select_category: 'Select Category',
    all_categories: 'All Categories',
    select_item: 'Select Item (Click for weight)',
    selected_items: 'Selected Items',
    add_record: 'Add Record',
    add_records: 'Add Records',
    consumer_name: 'Consumer Name',
    usage_type: 'Usage Type',
    source_location: 'Source Location',
    qty: 'Quantity',
    entry_by: 'Entry By',
    invoice: 'Invoice',
    type: 'Type',
    item_name: 'Item Name',
    search: 'Search...',
    loading: 'Loading...',
    no_records: 'No records found',
    last_50: 'Last 50 Records',
    activity_log: 'Activity Log',
    stock: 'Stock',
    from: 'From',
    usage: 'Usage',
    consumer: 'Consumer',
    chalan_bill: 'Chalan/Bill',
    language: 'Language',
    edit_item: 'Edit Item',
    add_item: 'Add Item',
    master_list_desc: 'Master list of items for stock',
    category: 'Category',
    add_category_first: 'Add category first',
    add_unit_first: 'Add unit first',
    par_level: 'Par Level (Min Stock)',
    edit: 'Edit',
    add: 'Add',
    cancel: 'Cancel',
    no_items_in_category: 'No items in this category',
    category_management: 'Category Management',
    new_category_name: 'New category name...',
    category_added: 'Category added',
    category_updated: 'Category updated',
    category_deleted: 'Category deleted',
    confirm_delete_category: 'Are you sure you want to delete this category?',
    unit_management: 'Unit Management',
    new_unit_name: 'New unit name...',
    unit_added: 'Unit added',
    unit_updated: 'Unit updated',
    unit_deleted: 'Unit deleted',
    confirm_delete_unit: 'Are you sure you want to delete this unit?',
    error_occurred: 'An error occurred',
    email_password_required: 'Email and password are required',
    account_created: 'Account created successfully',
    login_successful: 'Login successful',
    wrong_email_password: 'Wrong email or password',
    email_in_use: 'This email is already in use. Please login.',
    weak_password: 'Password should be at least 6 characters',
    login_disabled: 'Email/password login is not enabled. Please contact admin.',
    logout_successful: 'Logout successful',
    logout_error: 'Error logging out',
    create_new_account: 'Create New Account',
    stock_management_login: 'Stock Management Login',
    email: 'Email',
    your_email: 'Your Email',
    password: 'Password',
    your_password: 'Your Password',
    sign_up: 'Sign Up',
    login: 'Login',
    already_have_account: 'Already have an account? Login',
    need_account: 'Need an account? Sign Up',
    admin_login_note: 'Note: Use ghanshyampatel4721@gmail.com for admin login',
    
    // Reports & Dashboard
    total_items: 'Total Items',
    low_stock_items: 'Low Stock Items',
    recent_purchases: 'Recent Purchases',
    recent_consumptions: 'Recent Consumptions',
    reports_analysis: 'Reports & Analysis',
    print: 'Print',
    details: 'Details',
    pivot_table: 'Pivot Table',
    stock_report: 'Stock Report',
    usage_analysis: 'Usage Analysis',
    purchase_history: 'Purchase History',
    audit_accounting: 'Audit & Accounting',
    custom_report: 'Custom Report',
    drag_drop_desc: 'Drag and drop data to create custom reports',
    search_item_category: 'Search item or category...',
    low_stock: 'Low Stock',
    current_stock_summary: 'Current Stock Summary',
    status: 'Status',
    storage_report: 'Storage Report',
    expiry_tracking: 'Expiry Tracking',
    expiring_in_30_days: 'Items expiring in next 30 days',
    batch_bill_no: 'Batch/Bill No',
    days_left: 'Days Left',
    no_expiry_data: 'No expiry data available',
    usage_by_dept: 'Usage by Dept',
    top_10_consumed: 'Top 10 Consumed Items',
    supplier_source: 'Supplier/Source',
    stock_audit: 'Stock Audit',
    add_new_audit: 'Add New Audit',
    actual_stock: 'Actual Stock',
    notes: 'Notes',
    save: 'Save',
    variance: 'Variance',
    system_stock: 'System Stock',
    no_audit_records: 'No audit records yet',
    
    // Invoice
    generate_invoice: 'Generate Invoice',
    clear_all_data: 'Clear All Data',
    seed_data: 'Add Default Data',
    seeding: 'Adding Data...',
    confirm_clear_all: 'Are you sure you want to clear ALL items, categories, and units? This action cannot be undone.',
    all_data_cleared: 'All data cleared successfully',
    error_clearing_data: 'Error clearing data',
    confirm_delete_item: 'Are you sure you want to delete this item?',
    item_added: 'Item added successfully',
    item_updated: 'Item updated successfully',
    item_deleted: 'Item deleted successfully',
    confirm: 'Confirm',
    delete: 'Delete',
    confirm_delete_log: 'Are you sure you want to delete this log entry?',
    log_deleted: 'Log entry deleted successfully',
    edit_log: 'Edit Log Entry',
    log_updated: 'Log entry updated successfully',
    actions: 'Actions',
    sr_no: 'Sr No / ક્રમ',
    item_description: 'Item Description / વસ્તુની વિગત',
    auth_sign: 'Authorized Signature / સત્તાવાર સહી',
    comp_gen: 'This is a computer generated document. / આ કોમ્પ્યુટર દ્વારા જનરેટ થયેલ દસ્તાવેજ છે.',
    invoice_preview: 'Invoice Preview / ઇન્વોઇસ પ્રિવ્યૂ',
    download_pdf: 'Download PDF / PDF ડાઉનલોડ કરો',
    print_invoice: 'Print Invoice / ઇન્વોઇસ પ્રિન્ટ કરો',
    period: 'Period / સમયગાળો',
    generated_on: 'Generated On / બનાવેલ તારીખ',
    inv_date: 'Date / તારીખ',
    inv_qty: 'Quantity / જથ્થો',
    inv_category: 'Category / કેટેગરી',
    inv_usage_type: 'Usage Type / વપરાશનો પ્રકાર',
    inv_invoice: 'Invoice / ઇન્વોઇસ',
    inv_consumer: 'Consumer / લેનાર',
    daily_report: 'Daily Report',
    storage_location: 'Storage Location',
    main_store: 'Main Store (Kothar)',
    cold_storage: 'Cold Storage',
    details_for: 'Details for',
    select_date_details: 'Select a date to view details',
    total_purchase: 'Total Purchase',
    total_consumption: 'Total Consumption',
    clear_all: 'Clear All',
    audit_added: 'Stock audit record added successfully',
    net_change: 'Net Change',
    usage_namkeen: 'Namkeen',
    usage_bakery: 'Bakery',
    usage_staff_kitchen: 'Staff Kitchen',
    usage_caters: 'Caters',
    usage_swadham: 'Swadham',
    usage_santo: 'Santo',
    usage_internal: 'Internal',
    loc_main_store: 'Main Store',
    loc_cold_storage: 'Cold Storage',
    date_required: 'Date is required',
    category_required: 'Category is required',
    source_required: 'Source is required',
    unit_required: 'Unit is required',
    consumer_name_required: 'Consumer name is required',
    select_at_least_one: 'Please select at least one item',
    records_added_success: 'records added successfully',
    insufficient_stock: 'Insufficient stock!',
    available_stock: 'Available stock',
    par_level_placeholder: 'e.g. 10',
    'નમકીન': 'Namkeen',
    'બેકરી': 'Bakery',
    'સ્ટાફ રસોડુ': 'Staff Kitchen',
    'કેટરસ': 'Caters',
    'સ્વા.ધામ': 'Swadham',
    'પૂ.સંતો': 'Santo',
    'ઇન્ટરનલ': 'Internal',
    'મેઇન કોઠાર': 'Main Store',
    'કોલ્ડ સ્ટોરેજ': 'Cold Storage',
  },
  gu: {
    dashboard: 'ડેશબોર્ડ',
    purchase: 'ખરીદ',
    consumption: 'વપરાશ',
    history: 'ઇતિહાસ',
    logs: 'લોગ્સ',
    reports: 'રિપોર્ટ્સ',
    items: 'વસ્તુઓ',
    logout: 'લૉગઆઉટ',
    all: 'બધું',
    app_title: 'ભક્તિ ગૃહ ઉદ્યોગ',
    add_purchase: 'નવી ખરીદી ઉમેરો',
    add_consumption: 'નવો વપરાશ ઉમેરો',
    date: 'તારીખ',
    source: 'ખરીદ સ્થળ',
    chalan_no: 'ચલાણ નં',
    bill_no: 'બિલ નં',
    expiry_date: 'એક્સપાયરી તારીખ (વૈકલ્પિક)',
    unit: 'યુનિટ',
    select_category: 'કેટેગરી પસંદ કરો',
    all_categories: 'બધી કેટેગરી',
    select_item: 'વસ્તુ પસંદ કરો (વજન માટે ક્લિક કરો)',
    selected_items: 'પસંદ કરેલી વસ્તુઓ',
    add_record: 'રેકોર્ડ ઉમેરો',
    add_records: 'રેકોર્ડ ઉમેરો',
    consumer_name: 'વસ્તુ લઈ જનારનું નામ',
    usage_type: 'વપરાશનો પ્રકાર',
    source_location: 'ક્યાંથી લીધું?',
    qty: 'જથ્થો',
    entry_by: 'એન્ટ્રી કરનાર',
    invoice: 'ઇનવોઇસ',
    type: 'પ્રકાર',
    item_name: 'વસ્તુનું નામ',
    search: 'શોધો...',
    loading: 'લોડ થઈ રહ્યું છે...',
    no_records: 'કોઈ રેકોર્ડ મળ્યો નથી',
    last_50: 'છેલ્લા 50 રેકોર્ડ્સ',
    activity_log: 'એક્ટિવિટી લોગ',
    stock: 'સ્ટોક',
    from: 'કયાથી લીધી',
    usage: 'વપરાશ',
    consumer: 'લેનારનું નામ',
    chalan_bill: 'ચલાણ/બિલ',
    language: 'ભાષા',
    edit_item: 'વસ્તુ સુધારો',
    add_item: 'નવી વસ્તુ ઉમેરો',
    master_list_desc: 'સ્ટોક માટે વસ્તુઓની માસ્ટર યાદી',
    category: 'કેટેગરી',
    add_category_first: 'પહેલા કેટેગરી ઉમેરો',
    add_unit_first: 'પહેલા યુનિટ ઉમેરો',
    par_level: 'ન્યૂનતમ સ્ટોક (Par Level)',
    edit: 'સુધારો',
    add: 'ઉમેરો',
    cancel: 'રદ કરો',
    no_items_in_category: 'આ કેટેગરીમાં કોઈ વસ્તુ નથી',
    category_management: 'કેટેગરી મેનેજમેન્ટ',
    new_category_name: 'નવી કેટેગરીનું નામ...',
    category_added: 'કેટેગરી ઉમેરાઈ ગઈ',
    category_updated: 'કેટેગરી સુધારી દીધી',
    category_deleted: 'કેટેગરી કાઢી નાખી',
    confirm_delete_category: 'શું તમે ખરેખર આ કેટેગરી કાઢી નાખવા માંગો છો?',
    unit_management: 'યુનિટ મેનેજમેન્ટ',
    new_unit_name: 'નવા યુનિટનું નામ...',
    unit_added: 'યુનિટ ઉમેરાઈ ગયું',
    unit_updated: 'યુનિટ સુધારી દીધું',
    unit_deleted: 'યુનિટ કાઢી નાખ્યું',
    confirm_delete_unit: 'શું તમે ખરેખર આ યુનિટ કાઢી નાખવા માંગો છો?',
    error_occurred: 'ભૂલ આવી',
    email_password_required: 'ઈમેલ અને પાસવર્ડ જરૂરી છે',
    account_created: 'એકાઉન્ટ સફળતાપૂર્વક બન્યું',
    login_successful: 'સફળતાપૂર્વક લોગિન થયું',
    wrong_email_password: 'ખોટો ઈમેલ અથવા પાસવર્ડ',
    email_in_use: 'આ ઈમેલ પહેલેથી વપરાશમાં છે. કૃપા કરીને લોગિન કરો.',
    weak_password: 'પાસવર્ડ ઓછામાં ઓછો ૬ અક્ષરનો હોવો જોઈએ',
    login_disabled: 'ઈમેલ/પાસવર્ડ લોગિન સક્ષમ નથી. કૃપા કરીને એડમિનનો સંપર્ક કરો.',
    logout_successful: 'સફળતાપૂર્વક લોગઆઉટ થયું',
    logout_error: 'લોગઆઉટમાં ભૂલ આવી',
    create_new_account: 'નવું એકાઉન્ટ બનાવો',
    stock_management_login: 'સ્ટોક મેનેજમેન્ટ લોગિન',
    email: 'ઈમેલ',
    your_email: 'તમારો ઈમેલ',
    password: 'પાસવર્ડ',
    your_password: 'તમારો પાસવર્ડ',
    sign_up: 'સાઇન અપ કરો',
    login: 'લોગિન કરો',
    already_have_account: 'પહેલેથી એકાઉન્ટ છે? લોગિન કરો',
    need_account: 'નવું એકાઉન્ટ બનાવવું છે? સાઇન અપ કરો',
    admin_login_note: 'નોંધ: એડમિન લોગિન માટે ghanshyampatel4721@gmail.com નો ઉપયોગ કરો',

    // Reports & Dashboard
    total_items: 'કુલ વસ્તુઓ',
    low_stock_items: 'ઓછો સ્ટોક',
    recent_purchases: 'તાજેતરની ખરીદી',
    recent_consumptions: 'તાજેતરનો વપરાશ',
    reports_analysis: 'રિપોર્ટ્સ અને એનાલિસિસ',
    print: 'પ્રિન્ટ',
    details: 'વિગતો',
    pivot_table: 'પિવોટ ટેબલ',
    stock_report: 'સ્ટોક રિપોર્ટ',
    usage_analysis: 'વપરાશ વિશ્લેષણ',
    purchase_history: 'ખરીદીનો ઇતિહાસ',
    audit_accounting: 'ઓડિટ અને હિસાબ',
    custom_report: 'કસ્ટમ રિપોર્ટ',
    drag_drop_desc: 'ડેટાને ડ્રેગ અને ડ્રોપ કરીને તમારી જરૂરિયાત મુજબ રિપોર્ટ બનાવો',
    search_item_category: 'વસ્તુ અથવા કેટેગરી શોધો...',
    low_stock: 'ઓછો સ્ટોક',
    current_stock_summary: 'હાજર સ્ટોક સમરી',
    status: 'સ્થિતિ',
    storage_report: 'સ્ટોરેજ મુજબ રિપોર્ટ',
    expiry_tracking: 'એક્સપાયરી ટ્રેકિંગ',
    expiring_in_30_days: 'આગામી ૩૦ દિવસમાં એક્સપાયર થતી વસ્તુઓ',
    batch_bill_no: 'બેચ/બિલ નં',
    days_left: 'બાકી દિવસો',
    no_expiry_data: 'કોઈ એક્સપાયરી ડેટા ઉપલબ્ધ નથી',
    usage_by_dept: 'વિભાગ મુજબ વપરાશ',
    top_10_consumed: 'સૌથી વધુ વપરાતી વસ્તુઓ (Top 10)',
    supplier_source: 'સપ્લાયર/સોર્સ',
    stock_audit: 'સ્ટોક ઓડિટ',
    add_new_audit: 'નવું ઓડિટ ઉમેરો',
    actual_stock: 'હાજર જથ્થો',
    notes: 'નોંધ',
    save: 'સેવ કરો',
    variance: 'તફાવત',
    system_stock: 'સિસ્ટમ મુજબ',
    no_audit_records: 'હજી સુધી કોઈ ઓડિટ રેકોર્ડ નથી',
    
    // Invoice
    generate_invoice: 'ઇન્વોઇસ બનાવો',
    clear_all_data: 'બધો ડેટા સાફ કરો',
    seed_data: 'ડિફોલ્ટ ડેટા ઉમેરો',
    seeding: 'ડેટા ઉમેરાઈ રહ્યો છે...',
    confirm_clear_all: 'શું તમે ખરેખર બધી વસ્તુઓ, કેટેગરી અને યુનિટ કાઢી નાખવા માંગો છો? આ પ્રક્રિયા પાછી ખેંચી શકાશે નહીં.',
    all_data_cleared: 'બધો ડેટા સફળતાપૂર્વક સાફ થઈ ગયો',
    error_clearing_data: 'ડેટા સાફ કરવામાં ભૂલ આવી',
    confirm_delete_item: 'શું તમે ખરેખર આ વસ્તુ કાઢી નાખવા માંગો છો?',
    item_added: 'નવી વસ્તુ સફળતાપૂર્વક ઉમેરાઈ',
    item_updated: 'વસ્તુ સફળતાપૂર્વક સુધારાઈ',
    item_deleted: 'વસ્તુ કાઢી નાખવામાં આવી',
    confirm: 'ખાતરી કરો',
    delete: 'કાઢી નાખો',
    confirm_delete_log: 'શું તમે ખરેખર આ લોગ એન્ટ્રી કાઢી નાખવા માંગો છો?',
    log_deleted: 'લોગ એન્ટ્રી સફળતાપૂર્વક કાઢી નાખી',
    edit_log: 'લોગ એન્ટ્રી સુધારો',
    log_updated: 'લોગ એન્ટ્રી સફળતાપૂર્વક સુધારી',
    actions: 'ક્રિયાઓ',
    sr_no: 'Sr No / ક્રમ',
    item_description: 'Item Description / વસ્તુની વિગત',
    auth_sign: 'Authorized Signature / સત્તાવાર સહી',
    comp_gen: 'આ કોમ્પ્યુટર દ્વારા જનરેટ થયેલ દસ્તાવેજ છે.',
    invoice_preview: 'ઇન્વોઇસ પ્રિવ્યૂ',
    download_pdf: 'PDF ડાઉનલોડ કરો',
    print_invoice: 'ઇન્વોઇસ પ્રિન્ટ કરો',
    period: 'સમયગાળો',
    generated_on: 'બનાવેલ તારીખ',
    inv_date: 'તારીખ',
    inv_qty: 'જથ્થો',
    inv_category: 'કેટેગરી',
    inv_usage_type: 'વપરાશનો પ્રકાર',
    inv_invoice: 'ઇન્વોઇસ',
    inv_consumer: 'લેનાર',
    daily_report: 'દૈનિક રિપોર્ટ',
    storage_location: 'ક્યાં મૂકવાનું છે?',
    main_store: 'મેઇન કોઠાર',
    cold_storage: 'કોલ્ડ સ્ટોરેજ',
    details_for: 'ની વિગતો',
    select_date_details: 'વિગતો જોવા માટે તારીખ પસંદ કરો',
    total_purchase: 'કુલ ખરીદી',
    total_consumption: 'કુલ વપરાશ',
    clear_all: 'બધું સાફ કરો',
    audit_added: 'સ્ટોક ઓડિટ રેકોર્ડ સફળતાપૂર્વક ઉમેરાયો',
    net_change: 'ચોખ્ખો ફેરફાર',
    par_level_placeholder: 'દા.ત. 10',
    usage_namkeen: 'નમકીન',
    usage_bakery: 'બેકરી',
    usage_staff_kitchen: 'સ્ટાફ રસોડુ',
    usage_caters: 'કેટરસ',
    usage_swadham: 'સ્વા.ધામ',
    usage_santo: 'પૂ.સંતો',
    usage_internal: 'ઇન્ટરનલ',
    loc_main_store: 'મેઇન કોઠાર',
    loc_cold_storage: 'કોલ્ડ સ્ટોરેજ',
    date_required: 'તારીખ જરૂરી છે',
    category_required: 'કેટેગરી જરૂરી છે',
    source_required: 'ખરીદ સ્થળ જરૂરી છે',
    unit_required: 'યુનિટ જરૂરી છે',
    consumer_name_required: 'વસ્તુ લઈ જનારનું નામ જરૂરી છે',
    select_at_least_one: 'કૃપા કરીને ઓછામાં ઓછી એક વસ્તુ પસંદ કરો',
    records_added_success: 'રેકોર્ડ સફળતાપૂર્વક ઉમેરાયા',
    insufficient_stock: 'સ્ટોક અપૂરતો છે!',
    available_stock: 'ઉપલબ્ધ સ્ટોક',
  }
};

const LanguageContext = createContext<{
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: keyof typeof translations['en'] | string) => string;
} | null>(null);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<Language>(() => {
    return (localStorage.getItem('app_lang') as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('app_lang', lang);
  }, [lang]);

  const t = (key: string) => {
    return (translations[lang] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
